export const systemActions = [
    {
        key: 'dashboard',
        title: 'Ir al dashboard',
        description: 'Volver al panel principal del sistema.',
        category: 'General',
        routeName: 'dashboard',
        roles: ['Master', 'Administrador', 'Mesero', 'Cliente'],
        keywords: ['inicio', 'panel', 'dashboard', 'principal'],
        icon: 'dashboard',
    },
    {
        key: 'profile',
        title: 'Mi perfil',
        description: 'Ver y editar mis datos de cuenta.',
        category: 'Cuenta',
        routeName: 'profile.edit',
        roles: ['Master', 'Administrador', 'Mesero', 'Cliente'],
        keywords: ['perfil', 'cuenta', 'usuario', 'datos'],
        icon: 'user',
    },
    {
        key: 'employees-view',
        title: 'Visualizar empleados',
        description: 'Listar, buscar, editar y exportar empleados.',
        category: 'Administración',
        routeName: 'administracion.empleados.index',
        roles: ['Master', 'Administrador'],
        keywords: ['empleados', 'meseros', 'trabajadores', 'personal'],
        icon: 'users',
    },
    {
        key: 'employees-create',
        title: 'Añadir empleado',
        description: 'Registrar un nuevo empleado con rol Mesero.',
        category: 'Administración',
        routeName: 'administracion.empleados.index',
        query: { action: 'create' },
        roles: ['Master', 'Administrador'],
        keywords: ['crear empleado', 'añadir empleado', 'nuevo empleado', 'mesero'],
        icon: 'plus',
    },
    {
        key: 'clients-view',
        title: 'Visualizar clientes',
        description: 'Listar clientes, reservas y compras registradas.',
        category: 'Administración',
        routeName: 'administracion.clientes.index',
        roles: ['Master', 'Administrador'],
        keywords: ['clientes', 'compras', 'reservas'],
        icon: 'clients',
    },
    {
        key: 'clients-create',
        title: 'Añadir cliente',
        description: 'Registrar un nuevo cliente en el sistema.',
        category: 'Administración',
        routeName: 'administracion.clientes.index',
        query: { action: 'create' },
        roles: ['Master', 'Administrador'],
        keywords: ['crear cliente', 'añadir cliente', 'nuevo cliente'],
        icon: 'plus',
    },
    {
        key: 'admins-view',
        title: 'Visualizar administradores',
        description: 'Ver usuarios administradores del sistema.',
        category: 'Seguridad',
        routeName: 'administracion.administradores.index',
        roles: ['Master', 'Administrador'],
        keywords: ['administradores', 'admins', 'seguridad'],
        icon: 'shield',
    },
    {
        key: 'admins-create',
        title: 'Añadir administrador',
        description: 'Registrar un nuevo usuario administrador.',
        category: 'Seguridad',
        routeName: 'administracion.administradores.index',
        query: { action: 'create' },
        roles: ['Master'],
        keywords: ['crear administrador', 'añadir administrador', 'nuevo admin'],
        icon: 'shield',
    },
    {
        key: 'users-search',
        title: 'Buscar usuario',
        description: 'Consultar empleados, clientes y administradores.',
        category: 'Consultas',
        routeName: 'administracion.usuarios.buscar',
        roles: ['Master', 'Administrador'],
        keywords: ['buscar usuario', 'consultar usuario', 'estadisticas usuario'],
        icon: 'search',
    },
    {
        key: 'audit-log',
        title: 'Bitácora del sistema',
        description: 'Ver acciones realizadas por los usuarios.',
        category: 'Auditoría',
        routeName: 'administracion.bitacora.index',
        roles: ['Master', 'Administrador'],
        keywords: ['bitacora', 'auditoria', 'acciones', 'logs', 'registro'],
        icon: 'document',
    },
];

